import "../styles/globals.css";
import { Noto_Sans } from 'next/font/google'

const noto_sans = Noto_Sans({
  subsets: ['latin'],
  variable: '--font-noto-sans',
})


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${noto_sans.variable} font-sans`}>

        {children}

        </body>
    </html>
  )
}
